# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
    
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
          
      - name: clone stella
        run: git clone https://github.com/jctaoo/stella.git
          
      - name: install dependencies
        run: (cd stella && npm install)
      
      - name: copy gatsby config
        run: cp ./gatsby-config.ts ./stella
        
      - name: copy gatsby content
        run: cp -R ./content ./stella
        
      - name: copy favicon
        run: cp ./favicon.ico ./stella/static
        
      - name: run build
        run: (cd stella && npm run build)
      
      - name: copy CNAME
        run: cp ./CNAME ./stella/public
      
      - name: publish blog
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./stella/public
          commit_message: "[ci skip] Updates"
      
